version: '3.8'
services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
      container_name: es01
      environment:
        - node.name=es01
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - data:/usr/share/elasticsearch/data
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      networks:
        - eskb-net
    
    kibana:
      image: docker.elastic.co/kibana/kibana:7.8.0
      container_name: kib01
      ports:
        - 5601:5601
      environment:
        ELASTICSEARCH_URL: http://es01:9200
        ELASTICSEARCH_HOSTS: http://es01:9200
      networks:
        - eskb-net
volumes:
  data:
    driver: local
    # external: true
    # name: appdata

networks:
  eskb-net:
    driver: bridge
